// One-off: rasterize the icon geometry to PNGs at 16/32/48 px and pack them
// into a multi-size favicon.ico for browsers that don't render SVG favicons.
// Uses Node built-ins only (node:fs + node:zlib) — no external packages.
//
// Run with:  node scripts/build-favicon.mjs
//
// Keep the file under scripts/ so the icon can be regenerated by hand if the
// design changes. Update SVG and constants together to stay in sync.
import { writeFile } from 'node:fs/promises';
import { deflateSync } from 'node:zlib';

// Geometry (matches src/app/icon.svg).
const BG = [0x0a, 0x0a, 0x0a, 0xff]; // rounded square fill
const FG = [0xff, 0xff, 0xff, 0xff]; // bar fill
const TRANSPARENT = [0, 0, 0, 0];

// Normalized (0..1) on a 32-unit canvas:
const RADIUS_N = 7 / 32;
const BARS_N = [
  { x: 7 / 32, y: 9 / 32, w: 18 / 32, h: 3 / 32 },
  { x: 7 / 32, y: 14.5 / 32, w: 14 / 32, h: 3 / 32 },
  { x: 7 / 32, y: 20 / 32, w: 10 / 32, h: 3 / 32 },
];

/** Sample a single point in normalized [0,1) space — returns RGBA tuple. */
function sample(u, v) {
  // Rounded-square mask: outside the rect minus four corner caps.
  const r = RADIUS_N;
  const inSquare = u >= 0 && u < 1 && v >= 0 && v < 1;
  if (!inSquare) return TRANSPARENT;
  const inCorner =
    (u < r && v < r && Math.hypot(r - u, r - v) > r) ||
    (u > 1 - r && v < r && Math.hypot(u - (1 - r), r - v) > r) ||
    (u < r && v > 1 - r && Math.hypot(r - u, v - (1 - r)) > r) ||
    (u > 1 - r && v > 1 - r && Math.hypot(u - (1 - r), v - (1 - r)) > r);
  if (inCorner) return TRANSPARENT;

  for (const b of BARS_N) {
    if (u >= b.x && u < b.x + b.w && v >= b.y && v < b.y + b.h) return FG;
  }
  return BG;
}

/** Render an N×N RGBA buffer using 4× supersampling for anti-aliasing. */
function rasterize(size) {
  const SS = 4; // supersample factor
  const out = Buffer.alloc(size * size * 4);
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;
      for (let sy = 0; sy < SS; sy++) {
        for (let sx = 0; sx < SS; sx++) {
          const u = (px + (sx + 0.5) / SS) / size;
          const v = (py + (sy + 0.5) / SS) / size;
          const c = sample(u, v);
          r += c[0];
          g += c[1];
          b += c[2];
          a += c[3];
        }
      }
      const n = SS * SS;
      const o = (py * size + px) * 4;
      out[o] = Math.round(r / n);
      out[o + 1] = Math.round(g / n);
      out[o + 2] = Math.round(b / n);
      out[o + 3] = Math.round(a / n);
    }
  }
  return out;
}

// --- PNG encoding (RGBA 8-bit) ---

// CRC-32 (IEEE 802.3 polynomial 0xEDB88320). Used by PNG and ICO.
const CRC_TABLE = new Uint32Array(256);
for (let n = 0; n < 256; n++) {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  CRC_TABLE[n] = c;
}
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}

function encodePNG(rgba, width, height) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type: RGBA
  ihdr[10] = 0; // compression
  ihdr[11] = 0; // filter
  ihdr[12] = 0; // interlace

  // Prefix each scanline with filter byte 0 (None).
  const stride = width * 4;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0;
    rgba.copy(raw, y * (stride + 1) + 1, y * stride, y * stride + stride);
  }
  const idat = deflateSync(raw, { level: 9 });

  return Buffer.concat([sig, chunk('IHDR', ihdr), chunk('IDAT', idat), chunk('IEND', Buffer.alloc(0))]);
}

// --- ICO container (with embedded PNG entries — supported by every modern browser) ---

function packICO(pngs) {
  const HEADER = 6;
  const ENTRY = 16;
  const entries = pngs.length;
  const header = Buffer.alloc(HEADER);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2); // type 1 = icon
  header.writeUInt16LE(entries, 4);

  const dir = Buffer.alloc(ENTRY * entries);
  const data = [];
  let offset = HEADER + ENTRY * entries;
  pngs.forEach((png, i) => {
    const d = ENTRY * i;
    const w = png.width === 256 ? 0 : png.width;
    const h = png.height === 256 ? 0 : png.height;
    dir[d] = w;
    dir[d + 1] = h;
    dir[d + 2] = 0; // palette
    dir[d + 3] = 0; // reserved
    dir.writeUInt16LE(1, d + 4); // color planes
    dir.writeUInt16LE(32, d + 6); // bpp
    dir.writeUInt32LE(png.buf.length, d + 8);
    dir.writeUInt32LE(offset, d + 12);
    offset += png.buf.length;
    data.push(png.buf);
  });

  return Buffer.concat([header, dir, ...data]);
}

const sizes = [16, 32, 48];
const pngs = sizes.map((size) => ({
  width: size,
  height: size,
  buf: encodePNG(rasterize(size), size, size),
}));
const ico = packICO(pngs);
await writeFile('src/app/favicon.ico', ico);
console.log(
  `Wrote src/app/favicon.ico (${ico.length} bytes; embeds ${sizes
    .map((s) => `${s}x${s}`)
    .join(', ')} PNGs)`
);
